extends Node

var SAVE_LOCATION = "res://save/"
var ACTIVE_LOCATION = "active/"
var PERMANENT_LOCATION = "permanent/"

var ACTIVEFULL = SAVE_LOCATION + ACTIVE_LOCATION
var PERMANENTFULL = SAVE_LOCATION + PERMANENT_LOCATION
